# Generated by Django 4.2.1 on 2023-05-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todom',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
